# Generated by Django 2.2.1 on 2019-05-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='updated_datetime',
        ),
    ]
